# Generated by Django 3.2.7 on 2021-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockrankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=100, null=True)),
                ('marketcap', models.CharField(max_length=100, null=True)),
                ('revenue', models.CharField(max_length=100, null=True)),
                ('grossprofit', models.CharField(max_length=100, null=True)),
                ('operatingCashflow', models.CharField(max_length=100, null=True)),
                ('netprofit', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('employee', models.CharField(max_length=100, null=True)),
                ('dividendyield', models.CharField(max_length=100, null=True)),
                ('earningdate', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenbaggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
