# Generated by Django 3.2.7 on 2021-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrankings',
            name='netprofit',
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='companyname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='dividendyield',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='earningdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='employee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='grossprofit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='marketcap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='operatingCashflow',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='ticker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
