# Generated by Django 3.2.7 on 2021-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrankings',
            name='marketcap',
            field=models.FloatField(null=True),
        ),
    ]
