# Generated by Django 3.2.7 on 2021-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrankings', '0002_alter_stockrankings_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrankings',
            name='marketcap',
            field=models.IntegerField(null=True),
        ),
    ]
