# Generated by Django 3.2.7 on 2021-11-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockrankings', '0003_auto_20211102_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockrankings.stockrankings')),
            ],
        ),
    ]
