# Generated by Django 3.2.7 on 2021-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrankings', '0003_alter_stockrankings_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrankings',
            name='dividendyield',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='employee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='grossprofit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='netprofit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='operatingCashflow',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockrankings',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
    ]
